global using CommunityToolkit.Mvvm.ComponentModel;
global using Ebisx.POS.Presentation.ViewModels;
global using Ebisx.POS.Presentation.Views;
global using Ebisx.POS.Presentation.ViewModels.Popup;
global using Ebisx.POS.Presentation.Views.Popups;
global using Ebisx.POS.Presentation.Models;
global using Ebisx.POS.Presentation.Services;
global using System.Collections.ObjectModel;
global using Bogus;